### ISSUE TITLE
failed to load plugin

### ISSUE THREAD

**Issue by Ganji89420** [Quake1011/Admin-List#1]
20:05:22 [EROR] (cssharp:PluginManager) Failed to load plugin from D:\cs2\game\csgo\addons\counterstrikesharp\plugins\AdminList\AdminList.dll

**Comment by Quake1011** [comment]
Only my plugin throwing that?

**Comment by Ganji89420** [comment]
yes it was only ur plugin

**Comment by Quake1011** [comment]
> yes it was only ur plugin

there is more errors from this?

**Comment by Ganji89420** [comment]
20:16:11 [INFO] (cssharp:PluginContext) Loading plugin AdminList
20:16:11 [EROR] (cssharp:PluginManager) Failed to load plugin from /AMP/counter-strike2/730/game/csgo/addons/counterstrikesharp/plugins/AdminList/AdminList.dll
System.UnauthorizedAccessException: Access to the path '/AMP/counter-strike2/730/game/csgo/addons/counterstrikesharp/plugins/AdminList/Config.json' is denied.
---> System.IO.IOException: Permission denied
--- End of inner exception stack trace ---
at Interop.ThrowExceptionForIoErrno(ErrorInfo errorInfo, String path, Boolean isDirError)
at Microsoft.Win32.SafeHandles.SafeFileHandle.Open(String path, OpenFlags flags, Int32 mode, Func`4 createOpenException)
at Microsoft.Win32.SafeHandles.SafeFileHandle.Open(String fullPath, FileMode mode, FileAccess access, FileShare share, FileOptions options, Int64 preallocationSize, UnixFileMode openPermissions, Int64& fileLength, UnixFileMode& filePermissions, Func`4 createOpenException)
at System.IO.File.OpenHandle(String path, FileMode mode, FileAccess access, FileShare share, FileOptions options, Int64 preallocationSize)
at System.IO.File.WriteToFile(String path, FileMode mode, String contents, Encoding encoding)
at AdminList.AdminList.Load(Boolean hotReload) in E:\SteamLibrary\steamapps\common\Counter-Strike Global Offensive\game\csgo\addons\counterstrikesharp\plugins\AdminList\AdminList.cs:line 25
at CounterStrikeSharp.API.Core.Plugin.PluginContext.Load(Boolean hotReload) in /home/runner/work/CounterStrikeSharp/CounterStrikeSharp/managed/CounterStrikeSharp.API/Core/Plugin/PluginContext.cs:line 201
at CounterStrikeSharp.API.Core.Plugin.Host.PluginManager.LoadPlugin(String path) in /home/runner/work/CounterStrikeSharp/CounterStrikeSharp/managed/CounterStrikeSharp.API/Core/Plugin/Host/PluginManager.cs:line 52
at CounterStrikeSharp.API.Core.Plugin.Host.PluginManager.Load() in /home/runner/work/CounterStrikeSharp/CounterStrikeSharp/managed/CounterStrikeSharp.API/Core/Plugin/Host/PluginManager.cs:line 34

**Comment by Quake1011** [comment]
> 20:16:11 [INFO] (cssharp:PluginContext) Loading plugin AdminList 20:16:11 [EROR] (cssharp:PluginManager) Failed to load plugin from /AMP/counter-strike2/730/game/csgo/addons/counterstrikesharp/plugins/AdminList/AdminList.dll System.UnauthorizedAccessException: Access to the path '/AMP/counter-strike2/730/game/csgo/addons/counterstrikesharp/plugins/AdminList/Config.json' is denied. ---> System.IO.IOException: Permission denied --- End of inner exception stack trace --- at Interop.ThrowExceptionForIoErrno(ErrorInfo errorInfo, String path, Boolean isDirError) at Microsoft.Win32.SafeHandles.SafeFileHandle.Open(String path, OpenFlags flags, Int32 mode, Func`4 createOpenException) at Microsoft.Win32.SafeHandles.SafeFileHandle.Open(String fullPath, FileMode mode, FileAccess access, FileShare share, FileOptions options, Int64 preallocationSize, UnixFileMode openPermissions, Int64& fileLength, UnixFileMode& filePermissions, Func`4 createOpenException) at System.IO.File.OpenHandle(String path, FileMode mode, FileAccess access, FileShare share, FileOptions options, Int64 preallocationSize) at System.IO.File.WriteToFile(String path, FileMode mode, String contents, Encoding encoding) at AdminList.AdminList.Load(Boolean hotReload) in E:\SteamLibrary\steamapps\common\Counter-Strike Global Offensive\game\csgo\addons\counterstrikesharp\plugins\AdminList\AdminList.cs:line 25 at CounterStrikeSharp.API.Core.Plugin.PluginContext.Load(Boolean hotReload) in /home/runner/work/CounterStrikeSharp/CounterStrikeSharp/managed/CounterStrikeSharp.API/Core/Plugin/PluginContext.cs:line 201 at CounterStrikeSharp.API.Core.Plugin.Host.PluginManager.LoadPlugin(String path) in /home/runner/work/CounterStrikeSharp/CounterStrikeSharp/managed/CounterStrikeSharp.API/Core/Plugin/Host/PluginManager.cs:line 52 at CounterStrikeSharp.API.Core.Plugin.Host.PluginManager.Load() in /home/runner/work/CounterStrikeSharp/CounterStrikeSharp/managed/CounterStrikeSharp.API/Core/Plugin/Host/PluginManager.cs:line 34

Wrote that can't create config because haven't access to folder

**Comment by Ganji89420** [comment]
i got it to load, but it always says no admin online
![20231214153056_1](https://github.com/Quake1011/Admin-List/assets/151049632/17a99774-1896-4c6e-8a18-54e60637fa7c)
![Capture](https://github.com/Quake1011/Admin-List/assets/151049632/ded33716-c0ae-4125-83fe-b3b2e05c41be)
![20231214153216_1](https://github.com/Quake1011/Admin-List/assets/151049632/e4dbc604-dc88-4c65-be0d-c77ffc2b970e)

css_admins_list is showing i have access
